//Agregar articulos
export const AGREGAR_PRODUCTO = 'AGREGAR_PRODUCTO';
export const AGREGAR_PRODUCTO_EXITO = 'AGREGAR_PRODUCTO_EXITO';
export const AGREGAR_PRODUCTO_ERROR = 'AGREGAR_PRODUCTO_ERROR';

//Descarga de articulos
export const COMENZAR_DESCARGA_PRODUCTOS = 'COMENZAR_DESCARGA_PRODUCTOS';
export const DESCARGA_PRODUCTOS_EXITO = 'DESCARGA_PRODUCTOS_EXITO';
export const DESCARGA_PRODUCTOS_ERROR = 'DESCARGA_PRODUCTOS_ERROR';

//Descarga de articulos
export const COMENZAR_DESCARGA_ARTILOCA = 'COMENZAR_DESCARGA_ARTILOCA';
export const DESCARGA_ARTILOCA_EXITO = 'DESCARGA_ARTILOCA_EXITO';
export const DESCARGA_ARTILOCA_ERROR = 'DESCARGA_ARTILOCA_ERROR';


//Consulta articulos
export const OBTENER_PRODUCTO_CONSULTAR = 'OBTENER_PRODUCTO_CONSULTAR';
export const PRODUCTO_CONSULTAR_EXITO = 'PRODUCTO_CONSULTAR_EXITO';


//Elminacion del producto
export const OBTENER_PRODUCTO_ELIMINAR = 'OBTENER_PRODUCTO_ELIMINAR';
export const PRODUCTO_ELIMINADO_EXITO = 'PRODUCTO_ELIMINADO_EXITO';
export const PRODUCTO_ELIMINADO_ERROR = 'PRODUCTO_ELIMINADO_ERROR';

//Obtiene el producto a editar
export const OBTENER_PRODUCTO_EDITAR = 'OBTENER_PRODUCTO_EDITAR';
export const COMENZAR_EDICION_PRODUCTO = 'COMENZAR_EDICION_PRODUCTO';
export const PRODUCTO_EDITADO_EXITO = 'PRODUCTO_EDITADO_EXITO';
export const PRODUCTO_EDITADO_ERROR = 'PRODUCTO_EDITADO_ERROR';

//Alertas
export const MOSTRAR_ALERTA = 'MOSTRAR_ALERTA';
export const OCULTAR_ALERTA = 'OCULTAR_ALERTA';

//Descargar Unidades inventario
export const COMENZAR_DESCARGA_UNIDADES = 'COMENZAR_DESCARGA_UNIDADES';
export const DESCARGA_UNIDADES_EXITO = 'DESCARGA_UNIDADES_EXITO';
export const DESCARGA_UNIDADES_ERROR = 'DESCARGA_UNIDADES_ERROR';

//Agregar Unidades Inventario
export const AGREGAR_UNIDAD_MEDIDA = 'AGREGAR_UNIDAD_MEDIDA';
export const AGREGAR_UNIDAD_MEDIDA_EXITO = 'AGREGAR_UNIDAD_MEDIDA_EXITO';
export const AGREGAR_UNIDAD_MEDIDA_ERROR = 'AGREGAR_UNIDAD_MEDIDA_ERROR';

//Eliminar Unidades Medida
export const OBTENER_UNIDAD_MEDIDA_ELIMINAR = 'OBTENER_UNIDAD_MEDIDA_ELIMINAR';
export const UNIDAD_MEDIDA_ELIMINADO_EXITO = 'UNIDAD_MEDIDA_ELIMINADO_EXITO';
export const UNIDAD_MEDIDA_ELIMINADO_ERROR = 'UNIDAD_MEDIDA_ELIMINADO_ERROR';

//Obtiene el unidades a editar
export const OBTENER_UNIDADMEDI_EDITAR = 'OBTENER_UNIDADMEDI_EDITAR';
export const COMENZAR_EDICION_UNIDADMEDI = 'COMENZAR_EDICION_UNIDADMEDI';
export const UNIDADMEDI_EDITADO_EXITO = 'UNIDADMEDI_EDITADO_EXITO';
export const UNIDADMEDI_EDITADO_ERROR = 'UNIDADMEDI_EDITADO_ERROR';

//Descarga Tipos de empaques
export const COMENZAR_DESCARGA_TIPOEMPAQUE = 'COMENZAR_DESCARGA_TIPOEMPAQUE';
export const DESCARGA_TIPOEMPAQUE_EXITO = 'DESCARGA_TIPOEMPAQUE_EXITO';
export const DESCARGA_TIPOEMPAQUE_ERROR = 'DESCARGA_TIPOEMPAQUE_ERROR';

//Agregar Tipos Empaques
export const AGREGAR_TIPOEMPAQUE = 'AGREGAR_TIPOEMPAQUE';
export const AGREGAR_TIPOEMPAQUE_EXITO = 'AGREGAR_TIPOEMPAQUE_EXITO';
export const AGREGAR_TIPOEMPAQUE_ERROR = 'AGREGAR_TIPOEMPAQUE_ERROR';

//Eliminar Tipos empaques
export const OBTENER_TIPOEMPAQUE_ELIMINAR = 'OBTENER_TIPOEMPAQUE_ELIMINAR';
export const TIPOEMPAQUE_ELIMINADO_EXITO = 'TIPOEMPAQUE_ELIMINADO_EXITO';
export const TIPOEMPAQUE_ELIMINADO_ERROR = 'TIPOEMPAQUE_ELIMINADO_ERROR';

//Obtiene tipo empaque a editar
export const OBTENER_TIPOEMPAQUE_EDITAR = 'OBTENER_TIPOEMPAQUE_EDITAR';
export const COMENZAR_EDICION_TIPOEMPAQUE = 'COMENZAR_EDICION_TIPOEMPAQUE';
export const TIPOEMPAQUE_EDITADO_EXITO = 'TIPOEMPAQUE_EDITADO_EXITO';
export const TIPOEMPAQUE_EDITADO_ERROR = 'TIPOEMPAQUE_EDITADO_ERROR';

//Agregar bodeguero vendedor
export const AGREGAR_BODEGUERO_VENDEDOR = 'AGREGAR_BODEGUERO_VENDEDOR';
export const AGREGAR_BODEGUERO_VENDEDOR_EXITO = 'AGREGAR_BODEGUERO_VENDEDOR_EXITO';
export const AGREGAR_BODEGUERO_VENDEDOR_ERROR = 'AGREGAR_BODEGUERO_VENDEDOR_ERROR';

//Eliminar bodeguero vendedor
export const OBTENER_BODEGUERO_VENDEDOR_ELIMINAR = 'OBTENER_BODEGUERO_VENDEDOR_ELIMINAR';
export const BODEGUERO_VENDEDOR_ELIMINADO_EXITO = 'BODEGUERO_VENDEDOR_ELIMINADO_EXITO';
export const BODEGUERO_VENDEDOR_ELIMINADO_ERROR = 'BODEGUERO_VENDEDOR_ELIMINADO_ERROR';

//Editar bodeguero vendedor
export const OBTENER_BODEGUERO_VENDEDOR_EDITAR = 'OBTENER_BODEGUERO_VENDEDOR_EDITAR';
export const COMENZAR_EDICION_BODEGUERO_VENDEDOR = 'COMENZAR_EDICION_BODEGUERO_VENDEDOR';
export const BODEGUERO_VENDEDOR_EDITADO_EXITO = 'BODEGUERO_VENDEDOR_EDITADO_EXITO';
export const BODEGUERO_VENDEDOR_EDITADO_ERROR = 'BODEGUERO_VENDEDOR_EDITADO_ERROR';

//Descargar Bodeguero vendedor
export const COMENZAR_DESCARGA_BODEGUERO_VENDEDOR = 'COMENZAR_DESCARGA_BODEGUERO_VENDEDOR';
export const DESCARGA_BODEGUERO_VENDEDOR_EXITO = 'DESCARGA_BODEGUERO_VENDEDOR_EXITO';
export const DESCARGA_BODEGUERO_VENDEDOR_ERROR = 'DESCARGA_BODEGUERO_VENDEDOR_ERROR';

//Consulta articulos
export const OBTENER_BODEVENDE_CONSULTAR = 'OBTENER_BODEVENDE_CONSULTAR';
export const PRODUCTO_BODEVENDE_EXITO = 'PRODUCTO_BODEVENDE_EXITO';

//Consulta usuarios
export const COMENZAR_DESCARGA_USUARIO = 'COMENZAR_DESCARGA_USUARIO';
export const DESCARGA_USUARIO_LOGUEO = 'DESCARGA_USUARIO_LOGUEO';
export const DESCARGA_USUARIO_EXITO = 'DESCARGA_USUARIO_EXITO';
export const DESCARGA_USUARIO_ERROR = 'DESCARGA_USUARIO_ERROR';


//Agregar
export const AGREGAR = 'AGREGAR';
export const AGREGAR_EXITO = 'AGREGAR_EXITO';
export const AGREGAR_ERROR = 'AGREGAR_ERROR';

//Descarga
export const COMENZAR_DESCARGA = 'COMENZAR_DESCARGA';
export const DESCARGA_EXITO = 'DESCARGA_EXITO';
export const DESCARGA_ERROR = 'DESCARGA_ERROR';

//Consulta
export const OBTENER_CONSULTA = 'OBTENER_CONSULTA';
export const CONSULTAR_EXITO = 'CONSULTAR_EXITO';


//Elminacion
export const OBTENER_ELIMINAR = 'OBTENER_ELIMINAR';
export const ELIMINADO_EXITO = 'ELIMINADO_EXITO';
export const ELIMINADO_ERROR = 'ELIMINADO_ERROR';

//Obtiene el producto a editar
export const OBTENER_EDITAR = 'OBTENER_EDITAR';
export const COMENZAR_EDICION = 'COMENZAR_EDICION';
export const EDITADO_EXITO = 'EDITADO_EXITO';
export const EDITADO_ERROR = 'EDITADO_ERROR';


